export const ROLES = {
    SUPER_ADMIN: "SUPER_ADMIN",
  
    HOTEL_ADMIN: "HOTEL_ADMIN",
    HOTEL_CASHIER: "HOTEL_CASHIER",
    HOTEL_WAITER: "HOTEL_WAITER",
  
    KIOSK_ADMIN: "KIOSK_ADMIN",
    KIOSK_CASHIER: "KIOSK_CASHIER",
  
    KINYOZI_ADMIN: "KINYOZI_ADMIN",
    KINYOZI_OPERATOR: "KINYOZI_OPERATOR",
  
    CARWASH_ADMIN: "CARWASH_ADMIN",
    CARWASH_OPERATOR: "CARWASH_OPERATOR",
  
    PHARMACY_ADMIN: "PHARMACY_ADMIN",
    PHARMACY_CASHIER: "PHARMACY_CASHIER",
  };
  